version: '3'

services:
  dpcs-registry:
    image: registry:2
    container_name: dpcs-docker-registry
    ports:
      - 5000:5000
    restart: always
    volumes: 
      - ./volume:/var/lib/registry

  dpcs-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: dpcs-docker-registry-ui
    ports:
      - 8080:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: dpcs-registry
      ENV_DOCKER_REGISTRY_PORT: 5000