version: '3'
services:
  docker-registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - 59150:5000
    restart: always
    volumes: 
      - ./volume:/var/lib/registry
  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: docker-registry-ui
    ports:
      - 59151:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 59150